using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid;

namespace Process_Model
{
    public partial class GridForm : DevExpress.XtraEditors.XtraForm
    {
        public GridForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void gridControl1_DataSourceChanged(object sender, EventArgs e)
        {
            //gridControl1.RefreshDataSource();
        }

        private void gridView1_DataSourceChanged(object sender, EventArgs e)
        {
            gridControl1.RefreshDataSource();
            gridView1.Columns.Clear();
            gridView1.PopulateColumns();
            this.gridView1.OptionsView.ColumnAutoWidth = false;
            
            this.colQuestionID.Fixed = DevExpress.XtraGrid.Columns.FixedStyle.Left;
            this.colQuestionNo.Fixed = DevExpress.XtraGrid.Columns.FixedStyle.Left;
            this.colQuestionText.Fixed = DevExpress.XtraGrid.Columns.FixedStyle.Left;
            this.gridView1.BestFitColumns();
        }
    }
}